"""empty message

Revision ID: 026710aed723
Revises: d91ff7a12a1c
Create Date: 2017-11-22 21:45:36.349163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026710aed723'
down_revision = 'd91ff7a12a1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
