"""empty message

Revision ID: d3960fb9a57f
Revises: 026710aed723
Create Date: 2017-11-24 22:34:08.061646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3960fb9a57f'
down_revision = '026710aed723'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('participant', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'chats', 'users', ['participant'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_column('chats', 'participant')
    # ### end Alembic commands ###
